### ISSUE TITLE
MAFFT reverse complementing sequences

### ISSUE THREAD

**Issue by bmichanderson** [chrisjackson-pellicle/ParaGone#1]
It would be handy to have a flag to ensure MAFFT does not reverse complement input sequences if the user knows they should be all forward and in-frame. Alternatively, no reverse complement (flag `--adjustdirection` removed) could be default behaviour.

**Comment by chrisjackson-pellicle** [comment]
Hi @bmichanderson 

As of ParaGone version 0.0.7rc, MAFFT is prevented from reverse complementing input sequences (i.e., using the [--adjustdirection](https://mafft.cbrc.jp/alignment/software/adjustdirection.html) flag) in the first alignment step, unless the flag `--mafft_adjustdirection` is supplied. Note that all alignment steps after the first one do _not_ attempt to reverse complement any sequences, and that if a file of external outgroup sequences is provided, they should all be in the correct, forward, orientation.

Cheers,

Chris
