### ISSUE TITLE
--trimal_resoverlap forced to be an integer

### ISSUE THREAD

**Issue by LPDagallier** [chrisjackson-pellicle/ParaGone#3]
Hello,
Thank you for setting up this pipeline in such a clean and easy way!

I just noticed that the value of --trimal_resoverlap is forced to be an integer by the argument parser whereas it is supposed to be a number between 0 and 1.
I thus suggest to replace type=int with type=float in `paragone_subparsers.py` (line 146).

Cheers,
Léo-Paul

**Comment by chrisjackson-pellicle** [comment]
Hi @LPDagallier,

Thanks very much for pointing this out - it should be fixed in v1.0.0. 

I've uploaded the Linux conda package for v1.0.0, but I'm still working on the osX package, as there are some new issues with some of the Perl dependencies.

Cheers,

Chris

**Comment by LPDagallier** [comment]
Great, thanks @chrisjackson-pellicle !
