### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by TomHarrop** [chrisjackson-pellicle/ParaGone#4]
Hi, if there's a stable version of paragone, would you mind tagging a release for it on github? Thanks!

**Comment by chrisjackson-pellicle** [comment]
Hi @TomHarrop ,

Weeeeell, stable-ish :)

I've made a 1.0.0 release.

Cheers,

Chris

**Comment by TomHarrop** [comment]
Thanks @chrisjackson-pellicle 

I need version tags so I [added paragone to bioconda](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/paragone). The container is on [quay.io](https://quay.io/repository/biocontainers/paragone)  (with tags) and will be updated whenever you tag releases on this repo 

Can be used with nextflow etc.
